version: "3"
services:
  shop:
    image: kate-distsys/app
    ports:
      - "8080:8080"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      KATE_AUTH_BASEURL: http://auth:8080/
      SPRING_PROFILES_ACTIVE: shop
      DB_HOST: db
    depends_on:
      - db

  auth:
    image: kate-distsys/app
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: auth
      DB_HOST: db
    depends_on:
      - db


  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

